### ISSUE TITLE
Make Github Action use one/two container group for all the RavenDB instances required for a run

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.RavenDB#810]
- Probably split the single node form the cluster nodes into dedicated groups due to the restrictions of ACI.
- Find a way to replace certain values in the yaml for ACI

```yaml
apiVersion: 2019-12-01
location: switzerlandnorth
name: psw-ravendb-gateway-1
properties:
  containers:
  - name: singlenode
    properties:
      image: ravendb/ravendb:5.2-ubuntu-latest
      resources:
        requests:
          cpu: 2
          memoryInGb: 4
      ports:
      - port: 8080
      - port: 38888
      environmentVariables:
      - name: RAVEN_Security_UnsecuredAccessAllowed
        value: PublicNetwork
      - name: RAVEN_Setup_Mode
        value: None
      - name: RAVEN_License_Eula_Accepted
        value: true
      - name: RAVEN_ServerUrl
        value: "http://0.0.0.0:8080"
      - name: RAVEN_PublicServerUrl
        value: "http://psw-ravendb-gateway-1.switzerlandnorth.azurecontainer.io:8080"      
      - name: RAVEN_ServerUrl_Tcp
        value: "tcp://0.0.0.0:38888"
      - name: RAVEN_PublicServerUrl_Tcp
        value: "tcp://psw-ravendb-gateway-1.switzerlandnorth.azurecontainer.io:38888"
      livenessProbe:
        httpGet:
          path: "/"
          port: 8080
          scheme: http
        periodSeconds: 2  
  - name: leader
    properties:
      image: ravendb/ravendb:5.2-ubuntu-latest
      resources:
        requests:
          cpu: 2
          memoryInGb: 4
      ports:
      - port: 8081
      - port: 38890
      environmentVariables:
      - name: RAVEN_Security_UnsecuredAccessAllowed
        value: PublicNetwork
      - name: RAVEN_Setup_Mode
        value: None
      - name: RAVEN_License_Eula_Accepted
        value: true
      - name: RAVEN_ServerUrl
        value: "http://0.0.0.0:8081"
      - name: RAVEN_PublicServerUrl
        value: "http://psw-ravendb-gateway-1.switzerlandnorth.azurecontainer.io:8081"      
      - name: RAVEN_ServerUrl_Tcp
        value: "tcp://0.0.0.0:38890"
      - name: RAVEN_PublicServerUrl_Tcp
        value: "tcp://psw-ravendb-gateway-1.switzerlandnorth.azurecontainer.io:38890"
      livenessProbe:
        httpGet:
          path: "/"
          port: 8081
          scheme: http
        periodSeconds: 2
  - name: follower1
    properties:
      image: ravendb/ravendb:5.2-ubuntu-latest
      resources:
        requests:
          cpu: 2
          memoryInGb: 4
      ports:
      - port: 8082
      - port: 38891
      environmentVariables:
      - name: RAVEN_Security_UnsecuredAccessAllowed
        value: PublicNetwork
      - name: RAVEN_Setup_Mode
        value: None
      - name: RAVEN_License_Eula_Accepted
        value: true
      - name: RAVEN_ServerUrl
        value: "http://0.0.0.0:8082"
      - name: RAVEN_PublicServerUrl
        value: "http://psw-ravendb-gateway-1.switzerlandnorth.azurecontainer.io:8082"      
      - name: RAVEN_ServerUrl_Tcp
        value: "tcp://0.0.0.0:38891"
      - name: RAVEN_PublicServerUrl_Tcp
        value: "tcp://psw-ravendb-gateway-1.switzerlandnorth.azurecontainer.io:38891"
  - name: follower2
    properties:
      image: ravendb/ravendb:5.2-ubuntu-latest
      resources:
        requests:
          cpu: 2
          memoryInGb: 4
      ports:
      - port: 8083
      - port: 38892
      environmentVariables:
      - name: RAVEN_Security_UnsecuredAccessAllowed
        value: PublicNetwork
      - name: RAVEN_Setup_Mode
        value: None
      - name: RAVEN_License_Eula_Accepted
        value: true
      - name: RAVEN_ServerUrl
        value: "http://0.0.0.0:8083"
      - name: RAVEN_PublicServerUrl
        value: "http://psw-ravendb-gateway-1.switzerlandnorth.azurecontainer.io:8083"      
      - name: RAVEN_ServerUrl_Tcp
        value: "tcp://0.0.0.0:38892"
      - name: RAVEN_PublicServerUrl_Tcp
        value: "tcp://psw-ravendb-gateway-1.switzerlandnorth.azurecontainer.io:38892"                
  osType: Linux
  ipAddress:
    type: Public
    ports:
    - protocol: tcp
      port: 8080        
    - protocol: tcp
      port: 8081      
    - protocol: tcp
      port: 8082
    - protocol: tcp
      port: 8083
    - protocol: tcp
      port: 38888                 
    - protocol: tcp
      port: 38890
    - protocol: tcp
      port: 38891
    - protocol: tcp
      port: 38892                     
    dnsNameLabel: psw-ravendb-gateway-1   
tags: {exampleTag: tutorial}
type: Microsoft.ContainerInstance/containerGroups
```
